// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: CommonMsg.proto

package dbserver_grpc_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultDataState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
}

func (x *ResultDataState) Reset() {
	*x = ResultDataState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultDataState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultDataState) ProtoMessage() {}

func (x *ResultDataState) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultDataState.ProtoReflect.Descriptor instead.
func (*ResultDataState) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{0}
}

func (x *ResultDataState) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResultDataState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResultDataWithInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *ResultDataState `protobuf:"bytes,1,opt,name=State,proto3" json:"State"`
	Data  int64            `protobuf:"varint,2,opt,name=Data,proto3" json:"Data"`
}

func (x *ResultDataWithInt64) Reset() {
	*x = ResultDataWithInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultDataWithInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultDataWithInt64) ProtoMessage() {}

func (x *ResultDataWithInt64) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultDataWithInt64.ProtoReflect.Descriptor instead.
func (*ResultDataWithInt64) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{1}
}

func (x *ResultDataWithInt64) GetState() *ResultDataState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ResultDataWithInt64) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

type ResultDataWithString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *ResultDataState `protobuf:"bytes,1,opt,name=State,proto3" json:"State"`
	Data  string           `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data"`
}

func (x *ResultDataWithString) Reset() {
	*x = ResultDataWithString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultDataWithString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultDataWithString) ProtoMessage() {}

func (x *ResultDataWithString) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultDataWithString.ProtoReflect.Descriptor instead.
func (*ResultDataWithString) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{2}
}

func (x *ResultDataWithString) GetState() *ResultDataState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ResultDataWithString) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ResultDataWithBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *ResultDataState `protobuf:"bytes,1,opt,name=State,proto3" json:"State"`
	Data  bool             `protobuf:"varint,2,opt,name=Data,proto3" json:"Data"`
}

func (x *ResultDataWithBool) Reset() {
	*x = ResultDataWithBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultDataWithBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultDataWithBool) ProtoMessage() {}

func (x *ResultDataWithBool) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultDataWithBool.ProtoReflect.Descriptor instead.
func (*ResultDataWithBool) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{3}
}

func (x *ResultDataWithBool) GetState() *ResultDataState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ResultDataWithBool) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

var File_CommonMsg_proto protoreflect.FileDescriptor

var file_CommonMsg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x64, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x5f, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61, 0x74, 0x61, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x60, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x57, 0x69, 0x74, 0x68, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x5e, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x57, 0x69, 0x74, 0x68, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x64, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_CommonMsg_proto_rawDescOnce sync.Once
	file_CommonMsg_proto_rawDescData = file_CommonMsg_proto_rawDesc
)

func file_CommonMsg_proto_rawDescGZIP() []byte {
	file_CommonMsg_proto_rawDescOnce.Do(func() {
		file_CommonMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonMsg_proto_rawDescData)
	})
	return file_CommonMsg_proto_rawDescData
}

var file_CommonMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_CommonMsg_proto_goTypes = []interface{}{
	(*ResultDataState)(nil),      // 0: dbserver_grpc.ResultDataState
	(*ResultDataWithInt64)(nil),  // 1: dbserver_grpc.ResultDataWithInt64
	(*ResultDataWithString)(nil), // 2: dbserver_grpc.ResultDataWithString
	(*ResultDataWithBool)(nil),   // 3: dbserver_grpc.ResultDataWithBool
}
var file_CommonMsg_proto_depIdxs = []int32{
	0, // 0: dbserver_grpc.ResultDataWithInt64.State:type_name -> dbserver_grpc.ResultDataState
	0, // 1: dbserver_grpc.ResultDataWithString.State:type_name -> dbserver_grpc.ResultDataState
	0, // 2: dbserver_grpc.ResultDataWithBool.State:type_name -> dbserver_grpc.ResultDataState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_CommonMsg_proto_init() }
func file_CommonMsg_proto_init() {
	if File_CommonMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultDataState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultDataWithInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultDataWithString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultDataWithBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonMsg_proto_goTypes,
		DependencyIndexes: file_CommonMsg_proto_depIdxs,
		MessageInfos:      file_CommonMsg_proto_msgTypes,
	}.Build()
	File_CommonMsg_proto = out.File
	file_CommonMsg_proto_rawDesc = nil
	file_CommonMsg_proto_goTypes = nil
	file_CommonMsg_proto_depIdxs = nil
}
